### PR TITLE
Remove infinite loop in Subscriber and make pub/sub types more equal.

### PR DESCRIPTION
**Pull request by dwlnetnl**

### CODE REVIEW

**Comment by dwlnetnl** [comment]
Infinite loop in Subscriber.Listen is not fixed, sorry. I will try too debug the issue.

**Comment by dwlnetnl** [comment]
Ready to merge.

**Comment by chris-baynes** [comment]
Hi @dwlnetnl I like some of what you've done there (trying to bring the Subscriber more in line with the QueueSubscriber), but there were some ideas I'd like to keep of the original:
- The `Listen` methods should not return unless stopped. It could be that there's an error in the user defined handler, but that shouldn't stop the listener from processing the next message. What would be nice is to allow for a user defined logger so errors can be written there, rather than using the default from the `log` package.
- `Stop` should return the error (as you have done), but really those methods should be renamed to `Close` (along with the channels to `close`) - I'd say that's more idiomatic Go.
- I need to have another look at the `Subscriber` receive (we don't use that at Contiamo so I didn't spend the time yet) - closing the pubsub connection panics the underlying library in some circumstances.

I'd say this is library is still in beta so it's still ok to change the api to get things right. I'll try and have a look in the next few days at those things (if you don't have time yourself).

Cheers

**Comment by dwlnetnl** [comment]
On point 2, I had the same idea. I'm okay with a beta label, no problem.
In a few days I will come back to this pull request.

**Comment by dwlnetnl** [comment]
On point 1: If there is an error during listening/accepting, that error should be returned, like `http.ListenAndServe`. Indeed, not in normal operation. I guess an error handler would work: either an error is handled or a message, not both. Or change the `HandlerFunc` to accept an error argument and remove the returned error.

**Comment by chris-baynes** [comment]
`http.Serve` retries (after a wait) to `Accept` a new connection if there was a (temporary) network error. The individual goroutines started to handle each connection wrap any errors and panics from handler functions - these are just logged, but the http server continues to run and accept new connections.

The only time I can see that `http.ListenAndServe` returns an error is for non-temporary errors on the initial listenening, e.g. the port is already taken.

Since `ripple.Subscriber` is not a server, I can't think of any valid reason to return immediately from `Listen` (perhaps only for something like "invalid redis connection string"). The `HandlerFunc` already returns an error, so I think it's acceptable to just log this out.

**Comment by chris-baynes** [comment]
Closing - old and outdated. @dwlnetnl let me know if you're still using this!

**Pull request closed without merging**
